// Generated by gencpp from file step1/GetVFHDataRequest.msg
// DO NOT EDIT!


#ifndef STEP1_MESSAGE_GETVFHDATAREQUEST_H
#define STEP1_MESSAGE_GETVFHDATAREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace step1
{
template <class ContainerAllocator>
struct GetVFHDataRequest_
{
  typedef GetVFHDataRequest_<ContainerAllocator> Type;

  GetVFHDataRequest_()
    : goal_x(0.0)
    , goal_y(0.0)
    , threshold(0.0)  {
    }
  GetVFHDataRequest_(const ContainerAllocator& _alloc)
    : goal_x(0.0)
    , goal_y(0.0)
    , threshold(0.0)  {
  (void)_alloc;
    }



   typedef double _goal_x_type;
  _goal_x_type goal_x;

   typedef double _goal_y_type;
  _goal_y_type goal_y;

   typedef double _threshold_type;
  _threshold_type threshold;





  typedef boost::shared_ptr< ::step1::GetVFHDataRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::step1::GetVFHDataRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetVFHDataRequest_

typedef ::step1::GetVFHDataRequest_<std::allocator<void> > GetVFHDataRequest;

typedef boost::shared_ptr< ::step1::GetVFHDataRequest > GetVFHDataRequestPtr;
typedef boost::shared_ptr< ::step1::GetVFHDataRequest const> GetVFHDataRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::step1::GetVFHDataRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::step1::GetVFHDataRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::step1::GetVFHDataRequest_<ContainerAllocator1> & lhs, const ::step1::GetVFHDataRequest_<ContainerAllocator2> & rhs)
{
  return lhs.goal_x == rhs.goal_x &&
    lhs.goal_y == rhs.goal_y &&
    lhs.threshold == rhs.threshold;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::step1::GetVFHDataRequest_<ContainerAllocator1> & lhs, const ::step1::GetVFHDataRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace step1

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::step1::GetVFHDataRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::step1::GetVFHDataRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::step1::GetVFHDataRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::step1::GetVFHDataRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::step1::GetVFHDataRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::step1::GetVFHDataRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::step1::GetVFHDataRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fc63d46a0c19a3513335e12ec0019002";
  }

  static const char* value(const ::step1::GetVFHDataRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfc63d46a0c19a351ULL;
  static const uint64_t static_value2 = 0x3335e12ec0019002ULL;
};

template<class ContainerAllocator>
struct DataType< ::step1::GetVFHDataRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "step1/GetVFHDataRequest";
  }

  static const char* value(const ::step1::GetVFHDataRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::step1::GetVFHDataRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 goal_x\n"
"float64 goal_y\n"
"float64 threshold\n"
;
  }

  static const char* value(const ::step1::GetVFHDataRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::step1::GetVFHDataRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.goal_x);
      stream.next(m.goal_y);
      stream.next(m.threshold);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetVFHDataRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::step1::GetVFHDataRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::step1::GetVFHDataRequest_<ContainerAllocator>& v)
  {
    s << indent << "goal_x: ";
    Printer<double>::stream(s, indent + "  ", v.goal_x);
    s << indent << "goal_y: ";
    Printer<double>::stream(s, indent + "  ", v.goal_y);
    s << indent << "threshold: ";
    Printer<double>::stream(s, indent + "  ", v.threshold);
  }
};

} // namespace message_operations
} // namespace ros

#endif // STEP1_MESSAGE_GETVFHDATAREQUEST_H
