// Generated by gencpp from file step1/GetVFHData.msg
// DO NOT EDIT!


#ifndef STEP1_MESSAGE_GETVFHDATA_H
#define STEP1_MESSAGE_GETVFHDATA_H

#include <ros/service_traits.h>


#include <step1/GetVFHDataRequest.h>
#include <step1/GetVFHDataResponse.h>


namespace step1
{

struct GetVFHData
{

typedef GetVFHDataRequest Request;
typedef GetVFHDataResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetVFHData
} // namespace step1


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::step1::GetVFHData > {
  static const char* value()
  {
    return "7afd2a141a3ca51e86f2fbc885cf9fc7";
  }

  static const char* value(const ::step1::GetVFHData&) { return value(); }
};

template<>
struct DataType< ::step1::GetVFHData > {
  static const char* value()
  {
    return "step1/GetVFHData";
  }

  static const char* value(const ::step1::GetVFHData&) { return value(); }
};


// service_traits::MD5Sum< ::step1::GetVFHDataRequest> should match
// service_traits::MD5Sum< ::step1::GetVFHData >
template<>
struct MD5Sum< ::step1::GetVFHDataRequest>
{
  static const char* value()
  {
    return MD5Sum< ::step1::GetVFHData >::value();
  }
  static const char* value(const ::step1::GetVFHDataRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::step1::GetVFHDataRequest> should match
// service_traits::DataType< ::step1::GetVFHData >
template<>
struct DataType< ::step1::GetVFHDataRequest>
{
  static const char* value()
  {
    return DataType< ::step1::GetVFHData >::value();
  }
  static const char* value(const ::step1::GetVFHDataRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::step1::GetVFHDataResponse> should match
// service_traits::MD5Sum< ::step1::GetVFHData >
template<>
struct MD5Sum< ::step1::GetVFHDataResponse>
{
  static const char* value()
  {
    return MD5Sum< ::step1::GetVFHData >::value();
  }
  static const char* value(const ::step1::GetVFHDataResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::step1::GetVFHDataResponse> should match
// service_traits::DataType< ::step1::GetVFHData >
template<>
struct DataType< ::step1::GetVFHDataResponse>
{
  static const char* value()
  {
    return DataType< ::step1::GetVFHData >::value();
  }
  static const char* value(const ::step1::GetVFHDataResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // STEP1_MESSAGE_GETVFHDATA_H
