// Generated by gencpp from file get_destination/GetNextDestination.msg
// DO NOT EDIT!


#ifndef GET_DESTINATION_MESSAGE_GETNEXTDESTINATION_H
#define GET_DESTINATION_MESSAGE_GETNEXTDESTINATION_H

#include <ros/service_traits.h>


#include <get_destination/GetNextDestinationRequest.h>
#include <get_destination/GetNextDestinationResponse.h>


namespace get_destination
{

struct GetNextDestination
{

typedef GetNextDestinationRequest Request;
typedef GetNextDestinationResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetNextDestination
} // namespace get_destination


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::get_destination::GetNextDestination > {
  static const char* value()
  {
    return "09f8b596f17567f03b1180688311653f";
  }

  static const char* value(const ::get_destination::GetNextDestination&) { return value(); }
};

template<>
struct DataType< ::get_destination::GetNextDestination > {
  static const char* value()
  {
    return "get_destination/GetNextDestination";
  }

  static const char* value(const ::get_destination::GetNextDestination&) { return value(); }
};


// service_traits::MD5Sum< ::get_destination::GetNextDestinationRequest> should match
// service_traits::MD5Sum< ::get_destination::GetNextDestination >
template<>
struct MD5Sum< ::get_destination::GetNextDestinationRequest>
{
  static const char* value()
  {
    return MD5Sum< ::get_destination::GetNextDestination >::value();
  }
  static const char* value(const ::get_destination::GetNextDestinationRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::get_destination::GetNextDestinationRequest> should match
// service_traits::DataType< ::get_destination::GetNextDestination >
template<>
struct DataType< ::get_destination::GetNextDestinationRequest>
{
  static const char* value()
  {
    return DataType< ::get_destination::GetNextDestination >::value();
  }
  static const char* value(const ::get_destination::GetNextDestinationRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::get_destination::GetNextDestinationResponse> should match
// service_traits::MD5Sum< ::get_destination::GetNextDestination >
template<>
struct MD5Sum< ::get_destination::GetNextDestinationResponse>
{
  static const char* value()
  {
    return MD5Sum< ::get_destination::GetNextDestination >::value();
  }
  static const char* value(const ::get_destination::GetNextDestinationResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::get_destination::GetNextDestinationResponse> should match
// service_traits::DataType< ::get_destination::GetNextDestination >
template<>
struct DataType< ::get_destination::GetNextDestinationResponse>
{
  static const char* value()
  {
    return DataType< ::get_destination::GetNextDestination >::value();
  }
  static const char* value(const ::get_destination::GetNextDestinationResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GET_DESTINATION_MESSAGE_GETNEXTDESTINATION_H
