// Generated by gencpp from file my_turtle/orientation.msg
// DO NOT EDIT!


#ifndef MY_TURTLE_MESSAGE_ORIENTATION_H
#define MY_TURTLE_MESSAGE_ORIENTATION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_turtle
{
template <class ContainerAllocator>
struct orientation_
{
  typedef orientation_<ContainerAllocator> Type;

  orientation_()
    : direction()
    , value(0)  {
    }
  orientation_(const ContainerAllocator& _alloc)
    : direction(_alloc)
    , value(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _direction_type;
  _direction_type direction;

   typedef int64_t _value_type;
  _value_type value;





  typedef boost::shared_ptr< ::my_turtle::orientation_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_turtle::orientation_<ContainerAllocator> const> ConstPtr;

}; // struct orientation_

typedef ::my_turtle::orientation_<std::allocator<void> > orientation;

typedef boost::shared_ptr< ::my_turtle::orientation > orientationPtr;
typedef boost::shared_ptr< ::my_turtle::orientation const> orientationConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_turtle::orientation_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_turtle::orientation_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::my_turtle::orientation_<ContainerAllocator1> & lhs, const ::my_turtle::orientation_<ContainerAllocator2> & rhs)
{
  return lhs.direction == rhs.direction &&
    lhs.value == rhs.value;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::my_turtle::orientation_<ContainerAllocator1> & lhs, const ::my_turtle::orientation_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace my_turtle

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::my_turtle::orientation_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_turtle::orientation_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_turtle::orientation_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_turtle::orientation_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_turtle::orientation_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_turtle::orientation_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_turtle::orientation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "77bec05cc26700b375ca23f9f2183c08";
  }

  static const char* value(const ::my_turtle::orientation_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x77bec05cc26700b3ULL;
  static const uint64_t static_value2 = 0x75ca23f9f2183c08ULL;
};

template<class ContainerAllocator>
struct DataType< ::my_turtle::orientation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_turtle/orientation";
  }

  static const char* value(const ::my_turtle::orientation_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_turtle::orientation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string direction\n"
"int64 value\n"
;
  }

  static const char* value(const ::my_turtle::orientation_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_turtle::orientation_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.direction);
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct orientation_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_turtle::orientation_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_turtle::orientation_<ContainerAllocator>& v)
  {
    s << indent << "direction: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.direction);
    s << indent << "value: ";
    Printer<int64_t>::stream(s, indent + "  ", v.value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_TURTLE_MESSAGE_ORIENTATION_H
