// Generated by gencpp from file step1part2/GetNextDestination.msg
// DO NOT EDIT!


#ifndef STEP1PART2_MESSAGE_GETNEXTDESTINATION_H
#define STEP1PART2_MESSAGE_GETNEXTDESTINATION_H

#include <ros/service_traits.h>


#include <step1part2/GetNextDestinationRequest.h>
#include <step1part2/GetNextDestinationResponse.h>


namespace step1part2
{

struct GetNextDestination
{

typedef GetNextDestinationRequest Request;
typedef GetNextDestinationResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetNextDestination
} // namespace step1part2


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::step1part2::GetNextDestination > {
  static const char* value()
  {
    return "09f8b596f17567f03b1180688311653f";
  }

  static const char* value(const ::step1part2::GetNextDestination&) { return value(); }
};

template<>
struct DataType< ::step1part2::GetNextDestination > {
  static const char* value()
  {
    return "step1part2/GetNextDestination";
  }

  static const char* value(const ::step1part2::GetNextDestination&) { return value(); }
};


// service_traits::MD5Sum< ::step1part2::GetNextDestinationRequest> should match
// service_traits::MD5Sum< ::step1part2::GetNextDestination >
template<>
struct MD5Sum< ::step1part2::GetNextDestinationRequest>
{
  static const char* value()
  {
    return MD5Sum< ::step1part2::GetNextDestination >::value();
  }
  static const char* value(const ::step1part2::GetNextDestinationRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::step1part2::GetNextDestinationRequest> should match
// service_traits::DataType< ::step1part2::GetNextDestination >
template<>
struct DataType< ::step1part2::GetNextDestinationRequest>
{
  static const char* value()
  {
    return DataType< ::step1part2::GetNextDestination >::value();
  }
  static const char* value(const ::step1part2::GetNextDestinationRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::step1part2::GetNextDestinationResponse> should match
// service_traits::MD5Sum< ::step1part2::GetNextDestination >
template<>
struct MD5Sum< ::step1part2::GetNextDestinationResponse>
{
  static const char* value()
  {
    return MD5Sum< ::step1part2::GetNextDestination >::value();
  }
  static const char* value(const ::step1part2::GetNextDestinationResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::step1part2::GetNextDestinationResponse> should match
// service_traits::DataType< ::step1part2::GetNextDestination >
template<>
struct DataType< ::step1part2::GetNextDestinationResponse>
{
  static const char* value()
  {
    return DataType< ::step1part2::GetNextDestination >::value();
  }
  static const char* value(const ::step1part2::GetNextDestinationResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // STEP1PART2_MESSAGE_GETNEXTDESTINATION_H
